/**
 * Chinese (Simplified) translation catalogue.
 *
 * Keys are the English source strings exactly as they appear in the code, so a
 * missing entry degrades to English instead of breaking. This file is the only
 * place in the project that contains non-English text.
 *
 * 简体中文词条表。键就是代码里的英文原文，缺词条时自动回退英文。
 */
export const zh: Record<string, string> = {
  // --- Prompt-chunk origins, used as {origin} parameters ------------------
  "tool description": "工具描述",
  "tool input schema": "工具入参 schema",
  "skill": "skill",
  "subagent definition": "子 agent 定义",
  "slash command": "斜杠命令",
  "plugin manifest": "插件清单",
  "MCP server name": "MCP 服务器名",
  "markdown document": "Markdown 文档",
  "MCP server": "MCP 服务器",
  "tool": "工具",
  "server": "服务器",
  "Cyrillic": "西里尔",
  "Greek": "希腊",
  " and auto-confirms the install": "，而且自动确认安装",
  " while sending headers": "，并且还在发送请求头",

  "high-entropy secret": "高熵疑似密钥",
  "Anthropic API key": "Anthropic API key",
  "OpenAI API key": "OpenAI API key",
  "GitHub token": "GitHub token",
  "GitHub fine-grained token": "GitHub 细粒度 token",
  "GitLab token": "GitLab token",
  "AWS access key id": "AWS access key id",
  "Slack token": "Slack token",
  "Slack webhook": "Slack webhook",
  "Google API key": "Google API key",
  "Hugging Face token": "Hugging Face token",
  "Stripe secret key": "Stripe 私钥",
  "DigitalOcean token": "DigitalOcean token",
  "Telegram bot token": "Telegram bot token",
  "Private key block": "私钥块",
  "JSON Web Token": "JSON Web Token",

  // --- Severity labels ----------------------------------------------------
  "CRITICAL": "严重",
  "HIGH": "高危",
  "MEDIUM": "中危",
  "LOW": "低危",
  "INFO": "提示",
  "critical": "严重",
  "high": "高危",
  "medium": "中危",
  "low": "低危",
  "info": "提示",

  // --- Rule categories ----------------------------------------------------
  "Prompt injection & tool poisoning": "提示词注入与工具投毒",
  "Supply chain": "供应链",
  "Secrets & credentials": "密钥与凭据",
  "Execution & privilege": "执行与权限",
  "Network & exfiltration": "网络与数据外带",
  "Governance & hygiene": "治理与卫生",

  // --- Report chrome ------------------------------------------------------
  "scanning": "扫描",
  "{count} file": "{count} 个文件",
  "{count} files": "{count} 个文件",
  "{count} MCP server": "{count} 个 MCP 服务器",
  "{count} MCP servers": "{count} 个 MCP 服务器",
  "{count} tool": "{count} 个工具",
  "{count} tools": "{count} 个工具",
  "{count} skill": "{count} 个 skill",
  "{count} skills": "{count} 个 skill",
  "{count} plugin": "{count} 个插件",
  "{count} plugins": "{count} 个插件",
  "{count} hook": "{count} 个钩子",
  "{count} hooks": "{count} 个钩子",
  "No findings. Nothing in this target tripped a rule.": "没有发现问题，本次扫描目标没有命中任何规则。",
  "fix": "修复",
  "Summary": "结果汇总",
  "Risk score": "风险评分",
  "grade": "等级",
  "suppressed by baseline": "被 baseline 抑制",
  "in": "耗时",
  "Rule details": "规则详情",
  "Toolward security report": "Toolward 安全审计报告",
  "Target": "扫描目标",
  "Scanned at": "扫描时间",
  "Risk score:": "风险评分：",
  "Severity": "严重度",
  "Count": "数量",
  "No findings.": "没有发现问题。",
  "Findings": "发现列表",
  "Location": "位置",
  "Subject": "对象",
  "Detail": "说明",
  "Evidence": "证据",
  "Fix": "修复",
  "References": "参考",
  "Rule": "规则",
  "Default severity": "默认严重度",
  "Title": "标题",
  "Toolward rule catalogue": "Toolward 规则目录",
  "Generated by `toolward rules --format md`. Do not edit by hand.":
    "本文件由 `toolward rules --format md --lang zh` 生成，请勿手工编辑。",

  // --- CLI ----------------------------------------------------------------
  "Locked {count} entries (servers/tools/skills) → {path}": "已锁定 {count} 项（服务器/工具/skill）→ {path}",
  "Lock file not found at {path}. Run `toolward lock` first.": "找不到锁文件 {path}，请先运行 `toolward lock`。",
  "Accepted {count} findings into the baseline → {path}": "已把 {count} 条发现写入 baseline → {path}",
  "report written to {path}": "报告已写入 {path}",

  // Host discovery
  "Agent hosts found on this machine": "本机检测到的 Agent 宿主",
  note: "说明",
  "{found} of {total} known hosts detected. Scan them all with `toolward scan --hosts`.":
    "已知的 {total} 个宿主中检测到 {found} 个。用 `toolward scan --hosts` 一次全扫。",
  "also scan each project's .mcp.json and .claude/": "另外记得扫描每个项目的 .mcp.json 和 .claude/",
  "per project: .cursor/mcp.json": "项目内：.cursor/mcp.json",
  "per project: .vscode/mcp.json": "项目内：.vscode/mcp.json",
  "per workspace: .openworkbuddy/": "工作区内：.openworkbuddy/",
  "No known agent host configuration found on this machine.":
    "本机没有找到任何已知 Agent 宿主的配置。",
  "no findings": "无发现",

  // --- Internal errors ----------------------------------------------------
  "Rule execution error": "规则执行出错",
  "Rule {rule} threw: {error}": "规则 {rule} 抛出异常：{error}",
  "Please report this at https://github.com/CatCatUncle/toolward/issues":
    "请到 https://github.com/CatCatUncle/toolward/issues 反馈此问题。",

  // --- Rules (generated from the rule sources) ----------------------------
  "Shell command built from untrusted input": "用不可信输入拼接 shell 命令",
  "String-interpolated shell calls inside an extension turn any model-controlled argument into arbitrary command execution.":
    "扩展内部用字符串插值拼出的 shell 调用，会把任何由模型控制的参数变成任意命令执行。",
  "Use argv-array APIs (`execFile`, `spawn` without `shell: true`, `subprocess.run([...])`) and validate inputs.":
    "改用 argv 数组式 API（`execFile`、不带 `shell: true` 的 `spawn`、`subprocess.run([...])`），并校验输入。",
  "{rel}:{line} builds a shell command from interpolated input.": "{rel}:{line} 用插值输入拼接 shell 命令。",
  "Permission or sandbox bypass flag": "权限/沙箱绕过标志",
  "These flags disable the human confirmation and sandboxing the agent host relies on for every dangerous action.":
    "这些标志会关掉 agent 宿主对所有危险操作赖以生效的人工确认与沙箱。",
  "Remove the flag. If a workflow truly needs it, isolate it in a disposable container, never on a developer machine.":
    "删掉该标志。确实需要的流程，请放进一次性容器里跑，绝不要放在开发机上。",
  "\"{subject}\" uses {flag}.": "「{subject}」使用了 {flag}。",
  "{rel}:{line} uses {flag}.": "{rel}:{line} 使用了 {flag}。",
  "Blanket auto-approval of tool calls": "对工具调用的无差别自动放行",
  "Wildcard allow lists remove the last checkpoint between a poisoned tool description and a real action on your machine.":
    "通配符放行清单，会把「被投毒的工具描述」与「在你机器上的真实动作」之间的最后一道关卡去掉。",
  "Approve specific tools and specific command prefixes instead of `*`.": "改成逐个工具、逐条命令前缀放行，不要用 `*`。",
  "Server \"{name}\" auto-approves every tool call ({join}).": "服务器「{name}」对所有工具调用自动放行（{join}）。",
  "Server \"{name}\" auto-approves {autoApprove} tools without confirmation.":
    "服务器「{name}」有 {autoApprove} 个工具被免确认自动放行。",
  "permissions.allow contains wildcard entries ({entries}).": "permissions.allow 里存在通配符条目（{entries}）。",
  "permissions.defaultMode is \"{mode}\", so actions run without asking.":
    "permissions.defaultMode 是「{mode}」，操作会不经询问直接执行。",
  "Skill \"{name}\" requests wildcard tool access ({join}).": "Skill「{name}」申请了通配符工具权限（{join}）。",
  "Hook runs on every event with a broad matcher": "钩子以宽泛匹配器在每次事件上运行",
  "A hook with a `*` matcher sees every tool call and its arguments, and runs before you approve anything.":
    "匹配器为 `*` 的钩子能看到每一次工具调用及其参数，并且在你确认之前就已经运行。",
  "Scope the matcher to the tools you actually need, and keep the hook command short and auditable.":
    "把匹配器收敛到真正需要的工具上，并让钩子命令保持简短可审。",
  "The {event} hook matches every tool call and sends data over the network.": "{event} 钩子匹配所有工具调用，并且会把数据发到网络上。",
  "The {event} hook matches every tool call.": "{event} 钩子匹配所有工具调用。",
  "Persistence or self-modification of agent configuration": "持久化驻留或自改 agent 配置",
  "Writing to shell profiles, cron, launch agents or the host's own settings lets an extension survive its own removal.":
    "写入 shell 配置、cron、launch agent 或宿主自身的设置，会让扩展在被删掉之后依然存活。",
  "Remove the write. Installation steps belong in a documented, user-run command, not in a tool call.":
    "去掉这类写入。安装步骤应当是有文档、由用户手动执行的命令，而不是藏在工具调用里。",
  "{rel}:{line} writes to \"{match}\", creating persistence.": "{rel}:{line} 写入「{match}」，形成持久化驻留。",
  "The {event} hook touches a persistence location.": "{event} 钩子操作了持久化驻留位置。",
  "Overly broad filesystem scope": "文件系统授权范围过大",
  "Granting `/`, `$HOME` or `~` to a filesystem server exposes SSH keys, browser profiles and every other project on the machine.":
    "把 `/`、`$HOME` 或 `~` 授权给文件系统服务器，等于把 SSH 私钥、浏览器配置和机器上所有其他项目一起暴露。",
  "Grant one project directory per server and add a second server if you truly need a second scope.":
    "每个服务器只授权一个项目目录；确实需要第二个范围就再配一个服务器。",
  "Server \"{name}\" is granted the whole path \"{arg}\".": "服务器「{name}」被授予了整个路径「{arg}」。",
  "additionalDirectories grants \"{dir}\".": "additionalDirectories 授权了「{dir}」。",
  "Dynamic code evaluation": "动态代码求值",
  "`eval`, `new Function`, `pickle.loads` and unsafe YAML turn data into code, which is exactly what an injected payload needs.":
    "`eval`、`new Function`、`pickle.loads` 和不安全的 YAML 会把数据变成代码，而这正是注入载荷所需要的。",
  "Parse data with a data parser (`JSON.parse`, `yaml.safe_load`, `json.loads`) and drop the eval path entirely.":
    "用数据解析器解析数据（`JSON.parse`、`yaml.safe_load`、`json.loads`），彻底去掉 eval 这条路径。",
  "{rel}:{line} evaluates code at runtime via {call}.": "{rel}:{line} 通过 {call} 在运行时求值代码。",
  "Extension has no provenance metadata": "扩展缺少来源元数据",
  "Without an author, repository or licence there is no one to notify when the extension turns out to be malicious.":
    "没有作者、仓库或许可证信息，扩展一旦出问题，你连该通知谁都不知道。",
  "Add `author`, `repository`/`homepage` and `license` to the manifest, and `name` + `description` to skill frontmatter.":
    "在清单里补上 `author`、`repository`/`homepage` 和 `license`；skill frontmatter 补上 `name` 与 `description`。",
  "Plugin \"{name}\" is missing: {join}.": "插件「{name}」缺少：{join}。",
  "Skill \"{name}\" frontmatter is missing: {join}.": "Skill「{name}」的 frontmatter 缺少：{join}。",
  "Duplicate tool name across servers": "跨服务器的重名工具",
  "When two servers expose the same tool name the agent picks one by ordering, so a later install can silently take over an existing call site.":
    "两个服务器暴露同名工具时，agent 按顺序挑一个，后装的那个可以悄悄接管已有调用点。",
  "Namespace your tool names, or remove one of the two servers.": "给工具名加命名空间，或者删掉其中一个服务器。",
  "Tool \"{name}\" is exposed by {size} different sources: {join}.": "工具「{name}」被 {size} 个不同来源同时暴露：{join}。",
  "Tool name shadows a host built-in": "工具名遮蔽了宿主内置工具",
  "A tool called `read_file` or `bash` competes with the host's own tool of that name and can capture calls intended for it.":
    "叫 `read_file` 或 `bash` 的工具会与宿主同名工具竞争，可能截获本该发给宿主的调用。",
  "Prefix tool names with your product, e.g. `acme_read_file`.": "给工具名加上产品前缀，例如 `acme_read_file`。",
  "Tool \"{name}\" uses the same name as a common host built-in.": "工具「{name}」与常见宿主内置工具同名。",
  "Skill grants itself execution without declaring it": "Skill 隐式获得执行权但未声明",
  "A skill whose body runs shell commands but declares no `allowed-tools` inherits whatever the session already has.":
    "正文里会跑 shell 命令、却没声明 `allowed-tools` 的 skill，会直接继承当前会话已有的全部权限。",
  "Declare the minimum `allowed-tools` the skill needs, e.g. `Bash(git status:*), Read`.":
    "声明该 skill 真正需要的最小 `allowed-tools`，例如 `Bash(git status:*), Read`。",
  "Skill \"{name}\" runs shell commands but declares no allowed-tools.":
    "Skill「{name}」会执行 shell 命令，却没有声明 allowed-tools。",
  "Tool surface is not pinned against silent changes": "工具面未锁定，无法发现静默变更",
  "Without a lock file there is nothing to compare against, so a server that changes its tool descriptions after you approve it (a rug pull) goes unnoticed.":
    "没有锁文件就没有比对基准，服务器在你批准之后偷偷改掉工具描述（rug pull）你不会察觉。",
  "Run `toolward lock` to record the current surface, commit the lock file, then run `toolward verify` in CI.":
    "执行 `toolward lock` 记录当前工具面，把锁文件提交进仓库，并在 CI 里跑 `toolward verify`。",
  "No {lockFile} found for {servers} server(s) and {tools} tool(s).":
    "{servers} 个服务器、{tools} 个工具，但没有找到 {lockFile}。",
  "Instruction-override text in agent-visible content": "面向 agent 的内容里出现指令覆盖文本",
  "Text that tries to overrule the host's system prompt was found in content the agent ingests as authority.":
    "在 agent 会当作权威读取的内容里，发现试图覆盖宿主系统提示词的文本。",
  "Remove the override wording. Tool descriptions and skills should describe capability, never redefine the agent's rules.":
    "删掉这类覆盖措辞。工具描述和 skill 只应描述能力，不应重新定义 agent 的规则。",
  "The {origin} \"{subject}\" contains instruction-override wording.": "{origin}「{subject}」里含有指令覆盖措辞。",
  "Invisible Unicode characters": "不可见 Unicode 字符",
  "Zero-width, soft-hyphen or Unicode tag characters can carry instructions that a human reviewer literally cannot see.":
    "零宽字符、软连字符或 Unicode tag 字符可以夹带人眼完全看不见的指令。",
  "Strip the characters and re-review the plain text. Legitimate tool descriptions never need them.":
    "删掉这些字符后重新审阅纯文本。正常的工具描述不需要它们。",
  "{count} invisible character(s) found in the {origin} \"{subject}\".": "{origin}「{subject}」中发现 {count} 个不可见字符。",
  "Bidirectional control characters (Trojan Source)": "双向文本控制字符（Trojan Source）",
  "Bidi overrides make rendered text differ from the bytes the machine reads, so a reviewed description is not the executed one.":
    "Bidi 覆盖字符会让渲染出来的文本和机器实际读取的字节不一致，你审过的描述并不是真正生效的那份。",
  "Remove all U+202A-U+202E and U+2066-U+2069 characters and re-read the file.":
    "删除全部 U+202A–U+202E 与 U+2066–U+2069 字符后重新阅读文件。",
  "File contains bidirectional control characters at offset {index}.": "文件在偏移 {index} 处含有双向文本控制字符。",
  "Mixed-script name (homoglyph risk)": "混合字符集命名（同形字风险）",
  "A tool or server name mixing Latin with Cyrillic/Greek letters can impersonate a trusted name character-for-character.":
    "工具名或服务器名把拉丁字母与西里尔/希腊字母混用，可以逐字伪装成一个可信名字。",
  "Rename using ASCII only, and confirm you installed the package you meant to install.":
    "改用纯 ASCII 命名，并确认你装的确实是你想装的那个包。",
  "The {kind} \"{name}\" mixes Latin with {script} characters.": "{kind}「{name}」把拉丁字母与{script}字母混用。",
  "Instructions hidden in comments or invisible markup": "藏在注释/不可见标记里的指令",
  "HTML comments and zero-size or same-colour markup are invisible when rendered but fully visible to the model.":
    "HTML 注释、零号字或与背景同色的标记在渲染时看不见，但模型能完整读到。",
  "Delete the hidden block. If the text is genuinely needed, put it in plain visible prose.":
    "删掉隐藏块。如果内容确实需要，就写成可见的正文。",
  "An HTML comment in \"{subject}\" contains imperative instructions aimed at the model.":
    "「{subject}」中的 HTML 注释里含有针对模型的祈使指令。",
  "\"{subject}\" hides text from human readers with CSS while leaving it in the model's context.":
    "「{subject}」用 CSS 对人眼隐藏了文本，但这些文本仍在模型上下文里。",
  "Exfiltration instruction in agent-visible content": "面向 agent 的内容里出现数据外带指令",
  "The text instructs the agent to read local secrets or forward data to a third party — the core of a tool-poisoning attack.":
    "这段文本指示 agent 读取本地机密或把数据转发给第三方——这正是工具投毒攻击的核心。",
  "Do not install this extension. If it is yours, remove the instruction and move any real data flow behind an explicit, documented parameter.":
    "不要安装这个扩展。如果是你自己的，删掉该指令，把真实的数据流改成显式、有文档的参数。",
  "The {origin} \"{subject}\" instructs the agent to read or forward sensitive data.":
    "{origin}「{subject}」指示 agent 读取或转发敏感数据。",
  "Cross-tool shadowing instruction": "跨工具劫持（shadowing）指令",
  "The text tries to change how the agent uses other tools, letting one extension hijack calls meant for another.":
    "这段文本试图改变 agent 使用其他工具的方式，让一个扩展劫持本应发给另一个工具的调用。",
  "A tool description must only describe its own behaviour. Remove references to other tools' invocation order.":
    "工具描述只能描述自身行为。删掉对其他工具调用顺序的干预。",
  "The {origin} \"{subject}\" tries to control when other tools are used.": "{origin}「{subject}」试图控制其他工具何时被调用。",
  "Instruction to conceal behaviour from the user": "要求对用户隐瞒行为的指令",
  "Extensions that ask the agent to act silently defeat the human-in-the-loop that every agent host relies on.":
    "要求 agent 静默行事的扩展，会瓦解所有 agent 宿主赖以生存的人工确认环节。",
  "Remove the secrecy wording. Anything worth doing silently is worth a confirmation prompt.":
    "删掉这类保密措辞。值得静默执行的操作，更值得一次确认。",
  "The {origin} \"{subject}\" tells the agent to hide something from the user.":
    "{origin}「{subject}」要求 agent 对用户隐瞒内容。",
  "Fake system/authority markers": "伪造的系统/权威标记",
  "Tags such as <IMPORTANT> or [SYSTEM] impersonate the host's own prompt structure to borrow its authority.":
    "<IMPORTANT>、[SYSTEM] 这类标记在冒充宿主自身的提示词结构，以借用它的权威。",
  "Remove pseudo-system tags from descriptions and skill bodies.": "从描述和 skill 正文中删除伪系统标记。",
  "The {origin} \"{subject}\" uses a pseudo-system marker to claim authority.": "{origin}「{subject}」使用伪系统标记来冒充权威。",
  "Oversized tool description": "工具描述过长",
  "Very long descriptions are both a context-budget tax and a convenient place to bury an instruction.":
    "超长描述既吃上下文预算，也正好是埋指令的好地方。",
  "Keep tool descriptions under ~1000 characters and move detail into documentation.": "把工具描述控制在约 1000 字符内，细节放到文档里。",
  "Tool \"{name}\" has a {description}-character description.": "工具「{name}」的描述长达 {description} 个字符。",
  "Egress to a data-drop or tunnelling service": "外连到数据落地/隧道类服务",
  "These endpoints exist to collect whatever is sent to them, which makes them the default destination for stolen context.":
    "这些端点的存在意义就是接收别人发给它的任何内容，因此天然成为被窃取上下文的默认去处。",
  "Remove the endpoint. If you need a callback URL during development, keep it out of committed configuration.":
    "删掉该端点。开发期确实需要回调地址时，也不要提交进配置。",
  "{rel}:{line} points at {host}.": "{rel}:{line} 指向 {host}。",
  "Hard-coded IP endpoint": "硬编码 IP 端点",
  "A bare public IP has no certificate identity and no owner you can look up, so it cannot be reviewed like a domain.":
    "裸的公网 IP 没有证书身份、查不到归属，无法像域名那样被审核。",
  "Use a hostname with TLS, or document why the address is fixed.": "改用带 TLS 的域名；若地址必须固定，请写明原因。",
  "{rel}:{line} connects to the hard-coded address {address}.": "{rel}:{line} 连接到硬编码地址 {address}。",
  "Obfuscated payload": "被混淆的载荷",
  "Long encoded blobs in an extension hide the very thing a reviewer needs to read.": "扩展里的长编码块，恰好把审阅者最需要读的内容藏了起来。",
  "Decode it and commit the plain source, or document exactly what the blob is and where it came from.":
    "解码后把明文源码提交进来；或者写清楚这段编码块是什么、从哪来。",
  "{rel}:{line} contains a {length}-character encoded blob and decodes base64 at runtime.":
    "{rel}:{line} 含有 {length} 字符的编码块，且运行时会解码 base64。",
  "{rel}:{line} contains a {length}-character encoded blob.": "{rel}:{line} 含有 {length} 字符的编码块。",
  "Remote content executed at runtime": "运行时执行远程内容",
  "Fetching code and evaluating it means the audited version and the running version are never the same thing.":
    "先下载代码再求值，意味着你审过的版本和实际运行的版本永远不是同一个。",
  "Ship the code in the package and verify it by checksum; never evaluate a network response.":
    "把代码随包发布并用校验和验证；绝不要对网络响应做求值。",
  "{rel}:{line} fetches remote content and evaluates it.": "{rel}:{line} 拉取远程内容并对其求值。",
  "Out-of-band exfiltration primitive": "带外数据外带原语",
  "Raw sockets, `/dev/tcp` and DNS-encoded lookups move data out of networks that block ordinary HTTP egress.":
    "裸 socket、`/dev/tcp`、DNS 编码查询，可以在封禁普通 HTTP 出网的网络里把数据带走。",
  "Remove it. Legitimate extensions talk to documented HTTPS APIs.": "删掉。正经扩展只会访问有文档的 HTTPS API。",
  "{rel}:{line} opens an out-of-band channel: {call}": "{rel}:{line} 打开了带外通道：{call}",
  "The {event} hook opens an out-of-band channel.": "{event} 钩子打开了带外通道。",
  "Hard-coded credential in an agent configuration": "agent 配置里硬编码了凭据",
  "Agent configs are committed, synced and shared far more casually than .env files; a live key here is effectively published.":
    "agent 配置比 .env 更容易被提交、同步和分享，放在这里的有效密钥基本等于已经公开。",
  "Move the value into an environment variable reference (`${VAR}`) or your OS keychain, then rotate the exposed key.":
    "把值改成环境变量引用（`${VAR}`）或系统钥匙串，并立刻轮换已暴露的密钥。",
  "{detected} in {kind} \"{key}\" of server \"{name}\" ({value}).":
    "服务器「{name}」在 {kind} 字段「{key}」里带了 {detected}（{value}）。",
  "{kind} passed on the command line of server \"{name}\" ({value}).": "服务器「{name}」在命令行参数里传了 {kind}（{value}）。",
  "{name} found in {base} ({value}).": "在 {base} 中发现 {name}（{value}）。",
  "Credential in source, skill or documentation file": "源码/skill/文档里出现凭据",
  "Keys committed anywhere in the repository are retrievable from history forever, even after the file is deleted.":
    "仓库里任何位置提交过的密钥都会永久留在历史里，删文件也拿得回来。",
  "Rotate the credential first, then purge it from git history — deleting the line is not enough.":
    "先轮换凭据，再从 git 历史里彻底清除——只删掉那一行是不够的。",
  "{name} found in {rel} ({value}).": "在 {rel} 中发现 {name}（{value}）。",
  "Extension reads sensitive local files": "扩展读取本机敏感文件",
  "SSH keys, cloud credentials, browser cookies and shell history are the standard loot of a compromised extension.":
    "SSH 私钥、云凭据、浏览器 cookie、shell 历史，是被攻陷扩展最常拿走的东西。",
  "Remove the access. If a credential really is needed, take it as an explicit parameter with a documented scope.":
    "去掉这类访问。确实需要凭据时，应作为显式参数传入，并写明作用范围。",
  "{rel} references the sensitive path \"{path}\".": "{rel} 引用了敏感路径「{path}」。",
  "Server \"{name}\" is given access to \"{path}\" through its arguments.": "服务器「{name}」通过参数被授予了对「{path}」的访问权。",
  "Whole environment forwarded to a server": "把整个环境变量转发给服务器",
  "Passing the full process environment hands every unrelated key in your shell to that server.":
    "把整个进程环境传过去，等于把 shell 里所有无关密钥一并交给该服务器。",
  "List only the variables the server actually needs.": "只列出该服务器真正需要的变量。",
  "Server \"{name}\" forwards the entire environment ({key}).": "服务器「{name}」转发了整个环境变量（{key}）。",
  "Server \"{name}\" inherits the full environment via its arguments.": "服务器「{name}」通过参数继承了完整环境变量。",
  "Unpinned package executed on every agent start": "每次启动 agent 都会执行未锁版本的包",
  "npx/uvx style runners re-resolve the package each launch, so a later malicious release lands on your machine without any action from you.":
    "npx/uvx 这类运行器每次启动都会重新解析包，后续发布的恶意版本无需你做任何操作就会落到你机器上。",
  "Pin an exact version (e.g. `pkg@1.4.2`, `pkg==1.4.2`) and bump it deliberately after review.":
    "锁死确切版本（如 `pkg@1.4.2`、`pkg==1.4.2`），升级前先人工过一遍。",
  "Server \"{name}\" runs \`{runner} {spec}\` with no version pin{install}.":
    "服务器「{name}」执行 \`{runner} {spec}\`，没有锁版本{install}。",
  "Package installed from a non-registry source": "从非官方registry源安装的包",
  "Git URLs, tarballs and local paths bypass registry checks, provenance and yanking.":
    "git URL、tarball、本地路径会绕开 registry 的校验、来源追溯和撤包机制。",
  "Publish to a registry you control, or vendor the code into your repo so it is reviewable in diffs.":
    "发布到你能控制的 registry，或把代码 vendor 进仓库，让它能在 diff 里被审阅。",
  "Server \"{name}\" installs from a non-registry source.": "服务器「{name}」从非 registry 源安装。",
  "Remote script piped into a shell": "把远程脚本直接管道给 shell 执行",
  "`curl … | sh` hands arbitrary, unreviewed, unversioned code full execution rights on the developer machine.":
    "`curl … | sh` 等于把任意的、没审过、没版本的代码交给开发机完整执行。",
  "Download, pin by checksum, review, then execute as a separate committed step.": "先下载、按校验和锁定、人工审阅，再作为独立且入库的步骤执行。",
  "\"{subject}\" pipes a remotely fetched script straight into a shell.": "「{subject}」把远程下载的脚本直接管道给 shell 执行。",
  "Possible typosquat of a well-known MCP package": "疑似仿冒知名 MCP 包（typosquat）",
  "The package name is one or two edits away from a popular MCP server, the classic install-time hijack.":
    "包名与流行 MCP 服务器只差一两个字符，这是最典型的安装期劫持手法。",
  "Compare the name against the upstream project's README and check the publisher before installing.":
    "安装前对照上游项目 README 核对包名，并确认发布者。",
  "Package \"{name}\" is {distance} edit(s) away from \"{known}\".": "包名「{name}」与「{known}」只差 {distance} 个字符。",
  "Remote MCP server reached over plaintext HTTP": "通过明文 HTTP 连接远程 MCP 服务器",
  "Tool descriptions, arguments and auth headers all cross the network in clear text and can be rewritten in transit.":
    "工具描述、参数和鉴权头全部明文过网，且可在传输途中被改写。",
  "Use https://, or keep the server on localhost.": "改用 https://，或把服务器放在 localhost。",
  "Server \"{name}\" connects to {url} over plaintext HTTP{headers}.": "服务器「{name}」通过明文 HTTP 连接 {url}{headers}。",
  "Marketplace or plugin source is unpinned": "插件市场/插件来源未锁定",
  "A plugin source that tracks a moving branch installs whatever that branch holds at install time.":
    "指向浮动分支的插件来源，会在安装时装上该分支当时的任意内容。",
  "Reference a tag or commit SHA instead of a branch name.": "改为引用 tag 或 commit SHA，不要用分支名。",
  "Plugin \"{name}\" resolves its source without a tag or commit pin.": "插件「{name}」的来源没有锁定 tag 或 commit。",
  "Tool surface changed since it was approved": "工具面在批准之后发生了变化",
  "A server can serve a harmless description on the day you review it and a malicious one a week later. Comparing against a committed lock file is the only way to see that happen.":
    "服务器完全可以在你审核当天给一份无害描述，一周后换成恶意的。只有与已提交的锁文件比对，才能发现这件事。",
  "Review the diff before accepting it. If the change is legitimate, re-run `toolward lock` and commit the new file.":
    "先审阅 diff 再接受。变更确属正常的，重新执行 `toolward lock` 并提交新锁文件。",
  "New {kind} \"{id}\" appeared since the lock file was written.": "锁文件生成之后新出现了{kind}「{id}」。",
  "{kind} \"{id}\" changed: {from} → {to}.": "{kind}「{id}」已变更：{from} → {to}。",
  "{kind} \"{id}\" from the lock file is no longer present.": "锁文件中的{kind}「{id}」已不存在。",
};

/** Chinese CLI help screen. English lives in `src/cli.ts`. */
export function helpZh(version: string, lockFile: string): string {
  return `
Toolward ${version} —— AI agent 扩展安全审计工具。

用法
  toolward <命令> [路径...] [选项]

命令
  scan [路径...]         审计 MCP 服务器、skill、插件与连接器（默认命令）
  lock [路径...]         把当前工具面记录到 ${lockFile}
  verify [路径...]       把当前工具面与锁文件比对
  baseline [路径...]     把当前发现写成 baseline，让 CI 从绿色开始
  rules                  打印规则目录
  help                   显示本帮助

选项
  --format <格式>         pretty | json | md | sarif | compact   （默认 pretty）
  --out <文件>            把报告写入文件而不是标准输出
  --lang <en|zh>          报告语言                                （默认 en）
  --fail-on <严重度>      critical | high | medium | low | none   （默认 high）
  --min-severity <严重度> 隐藏低于该严重度的发现
  --only <规则号>         只跑这些规则，逗号分隔
  --exclude <通配符>      额外忽略的路径，逗号分隔
  --config <文件>         toolward.config.json 路径
  --baseline <文件>       baseline 文件路径
  --lock <文件>           lock/verify 使用的锁文件路径
  --compact               pretty 输出里省略修复建议行
  --no-color              关闭 ANSI 颜色
  --quiet                 不输出，只看退出码
  --version               打印版本号

退出码
  0  没有达到 --fail-on 阈值的发现
  1  存在达到 --fail-on 阈值的发现
  2  用法错误或运行时错误

Toolward 只做静态分析：不会启动服务器，不会安装依赖，也不会执行被审计的代码。

个人非商业使用免费；公司或商业使用需要授权：
https://github.com/CatCatUncle/toolward/blob/main/LICENSING.zh-CN.md
`;
}
